Remove 'using' keyword in message_filters
ros2/message_filters pull request #106
Opened 2023-12-07 19:17 UTC by clalancette

The 'using' keyword can cause problems if multiple APIs have the same named functions in different namespaces.  Further, we tend not to use it very much in ROS 2.

Thus, this PR just removes the keyword 'using' from all of the tests in message_filters.  There is also a minor amount of style cleanup; a follow-up PR will go deeper into that to attempt to get our linters running here.

2023-12-07 22:35 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=19960)](http://ci.ros2.org/job/ci_linux/19960/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=14430)](http://ci.ros2.org/job/ci_linux-aarch64/14430/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=20665)](http://ci.ros2.org/job/ci_windows/20665/)

2023-12-08 17:17 UTC, fujitatomoya requested changes
out of curiosity, are we not supposed to use `using`? what is the motivation for this change?

2023-12-08 17:17 UTC, fujitatomoya commented on test/msg_cache_unittest.cpp
> +  std::vector<std::shared_ptr<Msg const> > interval_data = cache.getInterval(rclcpp::Time(5, 0), rclcpp::Time(35, 0)) ;
```suggestion
  std::vector<std::shared_ptr<Msg const> > interval_data = cache.getInterval(rclcpp::Time(5, 0), rclcpp::Time(35, 0));
```

2023-12-08 17:17 UTC, fujitatomoya commented on test/msg_cache_unittest.cpp
> +  std::vector<std::shared_ptr<Msg const> > interval_data = cache.getInterval(rclcpp::Time(3, 0), rclcpp::Time(15, 0)) ;
```suggestion
  std::vector<std::shared_ptr<Msg const> > interval_data = cache.getInterval(rclcpp::Time(3, 0), rclcpp::Time(15, 0));
```

2023-12-08 17:32 UTC, clalancette commented
> out of curiosity, are we not supposed to use `using`? what is the motivation for this change?

It can cause subtle issues, particularly in header files.  The canonical example is doing something like this in a header file:

```
using std::placeholders::_1;
..

x = std::bind(&func, _1);
```

If another project wanted to `#include` your header file, but they did something like:

```
using boost::placeholders::_1;
```

Then it could cause things to break.  Also, the Google style guide says not to use it: https://google.github.io/styleguide/cppguide.html#Namespaces , because it can "pollute" the namespace.

2023-12-08 17:47 UTC, clalancette commented
Since the changes I pushed were only to spacing, I'm going to rely on the Rpr job here and just go ahead and merge this.  Thanks for the review!

2023-12-08 17:48 UTC, merged