Bugfix/segfault when getting surrounding interval of empty cache
ros2/message_filters pull request #116
Opened 2024-03-12 15:19 UTC by Cakem1x

This PR fixes a segfault that occurred to me when I tried to get a surrounding interval from a `message_filter::Cache` that was empty. See comment below for where/how.

The PR includes
* a test that should reproduce the segfault when executed without the fix.
* the fix of the segfault

Is it possible to get the fix also to other branches, specifically `humble` (but `iron` would probably also make sense)? That's the version I am using at the moment. I think the fix commit should be cherry-pickable. But the test commit probably needs some minor adaptation due to namespace changes.

Please let me know if I need to follow some specific procedure or provide more information for contributing. I didn't find any information.

2024-03-12 15:22 UTC, Cakem1x commented on include/message_filters/cache.h
segfault occurs in [line 229/235](https://github.com/ros2/message_filters/pull/116/files#diff-d4113f796930fd2e67a52312cf95f24e1337ec9338ab81947e0d68e9c44f72c7R235), when cache size is empty.
start_index and end_index are both `-1`, the current logic will then reserve `-1 - (-1) + 1 = 1` element and try to `push_back(cache_[-1]...);`.

2024-07-30 12:19 UTC, ahcorde requested changes
Do you mind to fix the conflicts ?

2024-07-30 12:19 UTC, ahcorde commented on test/msg_cache_unittest.cpp
> +  const std::vector<std::shared_ptr<Msg const> > interval_data = cache.getSurroundingInterval(rclcpp::Time(5, 0), rclcpp::Time(9, 0));
line too long, it should be less than 100 characters

2024-07-31 13:14 UTC, ahcorde requested changes
Still some linters failures https://build.ros2.org/job/Rpr__message_filters__ubuntu_noble_amd64/87/#showFailuresLink

2024-07-31 13:42 UTC, Cakem1x commented
> Still some linters failures https://build.ros2.org/job/Rpr__message_filters__ubuntu_noble_amd64/87/#showFailuresLink

Right, sorry, I had some issues with my local `ament_uncrustify` installation and tried to doctor the codestyle for this PR manually. Looks like codestyle is not a job for humans ;)
Fixing `ament_uncrustify` was worth it! Hope your CI's linter agrees with my local linter.

2024-07-31 13:49 UTC, Cakem1x commented
Just out of curiosity, do you use some specific tool (via IDE or CLI) to automatically format code to your CI's liking? `ament_uncrustify` has this nice `--reformat` option, but apparently some things are only caught by cpplint. And `ament_cpplint` can only complain, not fix.

2024-07-31 14:03 UTC, ahcorde requested changes

2024-07-31 14:03 UTC, ahcorde commented on test/msg_cache_unittest.cpp
> +      9, 0));
Indentation looks odd. Did you try something like this ?
```suggestion
    rclcpp::Time(5, 0), rclcpp::Time(9, 0));
```

2024-07-31 14:03 UTC, ahcorde commented on test/msg_cache_unittest.cpp
> +  EXPECT_EQ(interval_data.size(), (unsigned int) 0);  // empty cache shall return empty interval
```suggestion
  EXPECT_EQ(interval_data.size(), static_cast<unsigned int>(0));  // empty cache shall return empty interval
```

2024-08-01 12:19 UTC, Cakem1x commented
Looks like something is up with Jenkins, could you please re-trigger the job (when Jenkins is feeling better)? I think the failure is unrelated to the changes in this PR.

2024-08-01 13:36 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21598)](http://ci.ros2.org/job/ci_linux/21598/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15886)](http://ci.ros2.org/job/ci_linux-aarch64/15886/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1101)](http://ci.ros2.org/job/ci_linux-rhel/1101/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22316)](http://ci.ros2.org/job/ci_windows/22316/)

2024-08-01 13:56 UTC, clalancette commented
@ros-pull-request-builder retest this please

2024-08-01 16:10 UTC, ahcorde approved these changes

2024-08-01 16:10 UTC, merged

2024-08-01 16:11 UTC, ahcorde commented
@Cakem1x Thank you for iterating and the contribution

2024-08-01 16:12 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy