Adding Copyright Linter
ros2/message_filters pull request #122
Opened 2024-05-17 02:54 UTC by CursedRock17

Meant to be part of a group of PRs that will replace #120, this pull request adds just the copyright linters and resolves the issues that come with it. This pull request is in preparation of issue #29.

2024-05-17 08:04 UTC, ahcorde requested changes

2024-05-17 08:04 UTC, ahcorde commented on CMakeLists.txt
> +  find_package(ament_cmake_copyright)
Add the follwing to the package.xml
```xml
  <test_depend>ament_cmake_copyright</test_depend>
```

CI is failing https://build.ros2.org/job/Rpr__message_filters__ubuntu_noble_amd64/16/console

2024-05-17 15:34 UTC, clalancette requested changes

2024-05-17 15:34 UTC, clalancette commented on include/message_filters/subscriber.h
> +struct message_type <M, false>
I'm going to suggest we not make this change here.  In other words, I think this PR should strictly be about copyright; leave these other fixes to other PRs when we introduce the code linters.

2024-05-17 15:34 UTC, clalancette commented on include/message_filters/subscriber.h
> +class Subscriber
Same here.

2024-05-17 15:34 UTC, clalancette commented on include/message_filters/sync_policies/latest_time.h
> + * May also take an instance of a `rclcpp::Clock::SharedPtr` from `rclpp::Node::get_clock()`
Same here; let's put these in a different PR.

2024-05-17 15:34 UTC, clalancette commented on src/message_filters/__init__.py
> +
Same with this change; let's put it in a different PR.

2024-05-17 15:34 UTC, clalancette commented on src/message_filters/__init__.py
> +
And same here.

2024-05-17 15:34 UTC, clalancette commented on test/test_approxsync.py
> +
Let's make these changes in a different PR (same for all of the rest of the changes in this file).

2024-05-17 15:34 UTC, clalancette commented on test/test_message_filters_cache.py
> +
Let's make all of these changes to this file in a different PR.

2024-05-17 15:34 UTC, clalancette commented on test/test_message_traits.cpp
> +// Copyright 2024, Open Source Robotics Foundation, Inc. All rights reserved.
This one isn't correct; this should be:

```suggestion
// Copyright 2022, Kenji Brameld All rights reserved.
```

2024-05-17 15:34 UTC, clalancette commented on test/test_simple.cpp
> +// Copyright 2024, Open Source Robotics Foundation, Inc. All rights reserved.
```suggestion
// Copyright 2010, Willow Garage, Inc. All rights reserved.
```

2024-05-20 07:58 UTC, CursedRock17 commented
The copyrighting should be all filled out, just a lot of finicky whitespace issues I had to resolve

2024-05-20 08:30 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21109)](http://ci.ros2.org/job/ci_linux/21109/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15408)](http://ci.ros2.org/job/ci_linux-aarch64/15408/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21823)](http://ci.ros2.org/job/ci_windows/21823/)

2024-05-20 12:01 UTC, merged

2024-05-20 12:08 UTC, clalancette commented
Fantastic, this looks good to me.  Thanks for splitting this out.