[WIP] Adding cpplint
ros2/message_filters pull request #125
Opened 2024-05-22 05:36 UTC by CursedRock17

This pull request is part of a group of pull request which break apart #120, this particular pull request adds `cpplint` to `message_filters`.

2024-05-22 12:41 UTC, clalancette requested changes

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/message_event.h
> +// #include <rcutils/assert.h>
Let's just remove this (and the comment above).

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/parameter_adapter.h
> +// struct message_filters::ParameterAdapter<const std::shared_ptr<const Msg> &>
Just remove this.

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/sync_policies/approximate_time.h
> +// #include <rcutils/assert.h>
Just remove this (and the comment above).

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/sync_policies/approximate_time.h
> +    // printf("Creating candidate\n");
Just remove the line.

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/sync_policies/approximate_time.h
> +    // printf("Candidate created\n");
Remove the line.

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/sync_policies/approximate_time.h
> +    // printf("Publishing candidate\n");
Remove the line.

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/sync_policies/approximate_time.h
> +      // printf("]\n");
Remove all of these lines.

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/sync_policies/approximate_time.h
> +      // printf("start_index == %d, pivot_ == %d\n", start_index, pivot_);
Remove the line.

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/signal9.h
> +    explicit CallbackHelper9T<P0, P1, P2, P3, P4, P5, P6, P7, P8> * helper =
```suggestion
    CallbackHelper9T<P0, P1, P2, P3, P4, P5, P6, P7, P8> * helper =
```

2024-05-22 12:41 UTC, clalancette commented on include/message_filters/signal9.h
> +  CallbackHelper9T(const Callback & cb)
Why remove `explicit` here?

2024-05-28 00:10 UTC, CursedRock17 commented
So I've fixed the issues with `cpplint` though there are concerns with the `explicit` constructors. 
1. When it comes to `MessageEvent`, there was a call to [make its constructor explicit](https://github.com/ros2/message_filters/blob/rolling/include/message_filters/message_event.h#L119) in ROS 2, which is fine, but it means callbacks must follow the type of `const ConstMessagePtr &`. Thus, [this line](https://github.com/ros2/message_filters/blob/86e8c0c7fa5909447b963e50270edc5b2759074b/test/test_simple.cpp#L148) was changed to use the correct callbacks, creating errors otherwise. These changes now result in an API break, so is there a way to silence the explication warnings for this, should I create explicit constructors for each message type, or should we move on regardless?
2. There are also issues with the `explicit` keyword within `sync_policies`, in which the `Policy` must be constructed and then passed to the `Synchronizer` like [here](https://github.com/ros2/message_filters/blob/b8dbbf865506632139c9ea7202ea5a95e5cdaee2/test/test_exact_time_policy.cpp#L121-L122). Not a big deal work wise, but technically this will also cause an API break, which isn't a correct practice to follow, so should we also silence these errors instead of creating an `explicit` constructor within the policies?

2024-05-31 21:18 UTC, clalancette commented
> So I've fixed the issues with `cpplint` though there are concerns with the `explicit` constructors.

So technically, marking *any* of these constructors `explicit` is an API break; things that compiled before may no longer compile.

While that isn't necessarily a bad thing, we should probably decouple it from this PR so we can get this in.  In that case, what I'm going to suggest is that everywhere cpplint complains about explicit constructors, we add a `// NOLINT(explicit)` to the line.  Once we get this PR in, we can consider whether we actually want to do that API break separately.  Does that sound reasonable?

2024-06-03 11:11 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21203)](http://ci.ros2.org/job/ci_linux/21203/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15513)](http://ci.ros2.org/job/ci_linux-aarch64/15513/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21925)](http://ci.ros2.org/job/ci_windows/21925/)

2024-06-03 12:02 UTC, clalancette approved these changes
These changes look great to me with green CI.

@CursedRock17 Can I suggest that you open an issue to follow-up about the `NOLINT(runtime/explicit)` comments?

2024-06-03 13:09 UTC, merged