Deprecated qos_profile in Subscriber
ros2/message_filters pull request #127
Opened 2024-05-31 21:29 UTC by CursedRock17

This pull request is meant to solve this TODO: 
>   // TODO(wjwwood): deprecate in favor of API's that use `rclcpp::QoS` instead.

In which we use `rclcpp::QoS` in all of the `subscribe` methods in `message_filters`. Unfortunately when it comes to deprecating functions with default arguments, we can't just change the types of one element, [outlined here](https://en.cppreference.com/w/cpp/language/default_arguments):
> A redeclaration cannot introduce a default argument for a parameter for which a default argument is already visible (even if the value is the same)

So for this, I deprecated all the original methods, then just left the new `qos` argument uninitialized. I don't think this is necessarily the worst way to handle these changes because often times the user is going to need to adjust their `qos` settings anyways. Also, when we go to remove the deprecation in (I guess) [L-turtle](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html#deprecation-strategy), we can remove the old, deprecated functions, and re-add default values if it fits our needs. Though I don't think we can leave these methods with the same names and similar default params, I'm open to suggestion on how to improve the situation.

2024-06-03 09:07 UTC, ahcorde approved these changes
Running CI also on dependencies to check if we should update some downstream packages

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21202)](http://ci.ros2.org/job/ci_linux/21202/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15512)](http://ci.ros2.org/job/ci_linux-aarch64/15512/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21924)](http://ci.ros2.org/job/ci_windows/21924/)

2024-06-03 14:58 UTC, CursedRock17 commented
Alright, Pull requests have been opened for those two downstream warning messages.

2024-06-03 16:04 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21208)](http://ci.ros2.org/job/ci_linux/21208/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15517)](http://ci.ros2.org/job/ci_linux-aarch64/15517/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21929)](http://ci.ros2.org/job/ci_windows/21929/)

2024-06-03 19:35 UTC, ahcorde requested changes
There are two new warnings on Windows 

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\xutility(149,56): warning C4996: 'message_filters::Subscriber<Msg,rclcpp::Node>::Subscriber': use rclcpp::QoS instead of rmw_qos_profile_t [C:\ci\ws\build\message_filters\message_filters-test_subscriber.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\memory(2006): message : see reference to function template instantiation 'void std::_Construct_in_place<_Ty,std::shared_ptr<rclcpp::Node>&,const char(&)[11]>(_Ty &,std::shared_ptr<rclcpp::Node> &,const char (&)[11]) noexcept(false)' being compiled [C:\ci\ws\build\message_filters\message_filters-test_subscriber.vcxproj]

          with

          [

              _Ty=message_filters::Subscriber<Msg,rclcpp::Node>

          ]

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\memory(2725): message : see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<std::shared_ptr<rclcpp::Node>&,const char(&)[11]>(std::shared_ptr<rclcpp::Node> &,const char (&)[11])' being compiled [C:\ci\ws\build\message_filters\message_filters-test_subscriber.vcxproj]

          with

          [

              _Ty=message_filters::Subscriber<Msg,rclcpp::Node>

          ]

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\memory(2726): message : see reference to function template instantiation 'std::_Ref_count_obj2<_Ty>::_Ref_count_obj2<std::shared_ptr<rclcpp::Node>&,const char(&)[11]>(std::shared_ptr<rclcpp::Node> &,const char (&)[11])' being compiled [C:\ci\ws\build\message_filters\message_filters-test_subscriber.vcxproj]

          with

          [

              _Ty=message_filters::Subscriber<Msg,rclcpp::Node>

          ]
```

2024-06-05 08:40 UTC, ahcorde requested changes
Adding this
```cpp
rclcpp::QoS default_qos =
    rclcpp::QoS(rclcpp::QoSInitialization::from_rmw(rmw_qos_profile_default));
```
to the following should remove the warning https://github.com/ros2/message_filters/blob/9c97f73077a665d44f8bb19242f2111e08f68db1/test/test_subscriber.cpp#L177

2024-06-05 12:45 UTC, CursedRock17 commented
I updated the one `Subscriber` I was missing and also fixed up the docs so they wouldn't be deprecated.

2024-06-05 13:03 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21224)](http://ci.ros2.org/job/ci_linux/21224/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15533)](http://ci.ros2.org/job/ci_linux-aarch64/15533/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=698)](http://ci.ros2.org/job/ci_linux-rhel/698/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21944)](http://ci.ros2.org/job/ci_windows/21944/)

2024-06-05 15:34 UTC, ahcorde requested changes
Another downstream package in `rviz_default_plugins`

https://ci.ros2.org/job/ci_windows/21944/consoleText

2024-06-06 05:04 UTC, CursedRock17 commented
That's another package downstream prepped for patch, that being said, without a windows machine, is there any way for me to check which builds will fail ahead of time apart from cloning all the repos we use downstream then `grepping` for certain methods which have been chaned. That way in the future I can do this without having to restart CI for y'all everytime.

2024-06-06 08:13 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21234)](http://ci.ros2.org/job/ci_linux/21234/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15548)](http://ci.ros2.org/job/ci_linux-aarch64/15548/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=707)](http://ci.ros2.org/job/ci_linux-rhel/707/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21955)](http://ci.ros2.org/job/ci_windows/21955/)

2024-06-06 14:16 UTC, ahcorde approved these changes

2024-06-06 14:16 UTC, merged