Deprecating all C headers
ros2/message_filters pull request #135
Opened 2024-07-12 15:27 UTC by CursedRock17

This pull request is another and possibly the last needed addition to complete the breakdown of PR #120 in which all C headers are deprecated to C++ headers to solve this issue:
> But there is another problem here, and that is that message_filters isn't a "proper" C++ package. In particular, the header files still have the .h extension, and so our linters consider them to be C headers, not C++ headers

The PR appears to be super messy because I guess renaming files counts as making a whole new file in Git's eyes, but really each old file was renamed to have the `.hpp` tag with the correct header guard, then a new file `.h` was created with a warning message to use the C++ style header, so not too bad.

2024-07-12 15:32 UTC, ahcorde requested changes

2024-07-12 15:32 UTC, ahcorde commented on include/message_filters/cache.h
> +// Copyright 2024 Open Source Robotics Foundation, Inc.
```suggestion
// Copyright 2024 Open Source Robotics Foundation, Inc.
// All rights reserved.
```

2024-07-12 15:32 UTC, ahcorde commented on include/message_filters/cache.h
> +// Copyright 2024 Open Source Robotics Foundation, Inc.
to be consistent with the rest of headers, here and in the rest of files

2024-07-15 11:36 UTC, ahcorde commented
Updated downstream packages:
 - https://github.com/ros-perception/image_common/pull/320
 - https://github.com/ros-perception/point_cloud_transport/pull/94
 - https://github.com/ros2/geometry2/pull/702
 - https://github.com/ros2/rviz/pull/1239
 - https://github.com/ros-perception/image_pipeline/pull/1012

2024-07-16 15:50 UTC, ahcorde commented
I added rviz, geometry2, image_common and point_cloud_transport changes too

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21494)](http://ci.ros2.org/job/ci_linux/21494/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15777)](http://ci.ros2.org/job/ci_linux-aarch64/15777/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=993)](http://ci.ros2.org/job/ci_linux-rhel/993/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22208)](http://ci.ros2.org/job/ci_windows/22208/)

2024-07-17 09:46 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21497)](http://ci.ros2.org/job/ci_linux/21497/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15779)](http://ci.ros2.org/job/ci_linux-aarch64/15779/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=995)](http://ci.ros2.org/job/ci_linux-rhel/995/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22210)](http://ci.ros2.org/job/ci_windows/22210/)

2024-07-18 20:44 UTC, ahcorde approved these changes

2024-07-18 20:45 UTC, merged

2024-07-18 22:07 UTC, CursedRock17 commented
Since this pull request was meant to be the last of pull request #120, I feel we should be able to close both #120 and its respective issue of #29 since linters have been totally added. We just have to revisit this pull request in I believe L-turtle to remove the deprecations.

2024-07-19 16:04 UTC, ahcorde commented
> Since this pull request was meant to be the last of pull request #120, I feel we should be able to close both #120 and its respective issue of #29 since linters have been totally added. We just have to revisit this pull request in I believe L-turtle to remove the deprecations.

See this comment https://github.com/ros2/message_filters/pull/120