[LatestTimeSync] Fix crash when Synchronizer is started before the messges are available.
ros2/message_filters pull request #136
Opened 2024-07-24 11:29 UTC by destogl

This is tested on `humble` it might be the same issue on master too.

### Issue

When synchronizer with LastTime is used and messages are not yet available on subsribers, the `prev` time variable get somehow different time source then `now` variable.
I have tried to set the clock in the constructor and manually later using `setClock` method.
Nothing has helped.

### Proposed solution
Catch `str::runtime_error` thrown when differnet time sources are tried to be substracted from each other.
Here the example output with error with 4 sensors that sometimes need more time to come up.

```
[laser_scan_unifier-1] Previous time is: 94704.3
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Exception: can't subtract times with different time sources [1 != 0]
[laser_scan_unifier-1] Previous time is: 94704.3
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Exception: can't subtract times with different time sources [1 != 0]
[laser_scan_unifier-1] Previous time is: 94704.3
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Exception: can't subtract times with different time sources [1 != 0]
[laser_scan_unifier-1] Previous time is: 1.72182e+09
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Previous time is: 0
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Exception: can't subtract times with different time sources [1 != 0]
[laser_scan_unifier-1] Previous time is: 1.72182e+09
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Previous time is: 0
[laser_scan_unifier-1] Current time is: 1.72182e+09
[laser_scan_unifier-1] Exception: can't subtract times with different time sources [1 != 0]
```

After few more such outputs, when messages are there, everything works fine!

We are using this in ROS 2 port of [`laser_scan_unifier`](https://github.com/StoglRobotics-forks/laser_scan_unifier/tree/ros2-scan-unifier)

### Disclamer

I would love to solve the issue in its core, but couldn't get better place or way to do this from the code, as it seems that during initilisation `prev` variable get the wrong time source, independently from the provided clock.

2024-07-24 11:32 UTC, destogl commented on include/message_filters/sync_policies/latest_time.h
> +
Remove testing include.

```suggestion
```

2024-07-24 11:35 UTC, ahcorde requested changes
@destogl do you mind to retarget this to rolling ? then I can backport to other distros

2024-07-30 12:14 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21579)](http://ci.ros2.org/job/ci_linux/21579/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15868)](http://ci.ros2.org/job/ci_linux-aarch64/15868/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1077)](http://ci.ros2.org/job/ci_linux-rhel/1077/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22299)](http://ci.ros2.org/job/ci_windows/22299/)

2024-07-30 13:35 UTC, merged

2024-07-30 13:36 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy iron