Add temporal offset between topics between ApproximateTimeSynchronizer
ros2/message_filters pull request #154
Opened 2024-10-21 13:24 UTC by clement-chupin

To be able to keep volontary a temporal offset between topics, to keep a message before another for example.

2024-10-25 08:52 UTC, ahcorde requested changes
Thank you for your contribution, Do you mind ato add a test  ?

2024-10-25 08:52 UTC, ahcorde commented on src/message_filters/__init__.py
> +    The ``queue_offset`` option allow to have temporal offset between subsribers
```suggestion
    The ``queue_offset`` option allow to have temporal offset between subscribers
```

2024-10-31 16:12 UTC, clement-chupin reviewed
I have added the test for my changes, thanks for your work

2024-12-13 09:09 UTC, ahcorde commented
Pulls: ros2/message_filters#154
Gist: https://gist.githubusercontent.com/ahcorde/a00bbf2f4f5246d24ff9a4c27179a2b4/raw/2f6027c94bbb8fb4a308d2179b7406bc18c48015/ros2.repos
BUILD args:  --packages-above-and-dependencies message_filters --packages-above-and-dependencies message_filters
TEST args:  --packages-above message_filters --packages-above message_filters
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14954
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=22266)](http://ci.ros2.org/job/ci_linux/22266/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=16527)](http://ci.ros2.org/job/ci_linux-aarch64/16527/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1790)](http://ci.ros2.org/job/ci_linux-rhel/1790/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=23049)](http://ci.ros2.org/job/ci_windows/23049/)

2024-12-13 15:07 UTC, merged