Add policy to store the latest messages
ros2/message_filters pull request #38
Opened 2019-08-31 18:22 UTC by jcmonteiro

Add policies to store the most recent received messages (based on their timestamp or on the order of arrival); These policies **do not** call any callback automatically. It is up to the programmer to call the `call` method when it is time to process the information.

These policies are meant to be used in networks where information is processed periodically.

2023-09-08 01:39 UTC, ZhenshengLee commented
> It is up to the programmer to call the `call` method when it is time to process the information.

@jcmonteiro 

Could you provide some docs to explain the motivation of this policy? or more info about why, when and how we should use this policy?

2023-12-07 19:09 UTC, clalancette requested changes
I know this is really old, so sorry for the long delay in looking at it.  If you'd like to give up on getting this in, I'd totally understand.

If you'd still like to move forward, I've left some stuff inline to fix.  Also, I'm not a huge fan of the terminology "latest" to describe this policy.  While it is accurate, I don't think it will be hugely meaningful to people, and seems too close to "latest_time" (which we already have).  Maybe we can rename it to "user controlled", or something like that.

2023-12-07 19:09 UTC, clalancette commented on include/message_filters/sync_policies/latest_stamped.h
> +#define MESSAGE_FILTERS__SYNC_LatestStamped_H_
```suggestion
#ifndef MESSAGE_FILTERS__SYNC_LATESTSTAMPED_H_
#define MESSAGE_FILTERS__SYNC_LATESTSTAMPED_H_
```

2024-01-11 07:21 UTC, ZhenshengLee commented
@jcmonteiro  Friendly ping for updates.

2024-01-11 12:30 UTC, ZhenshengLee commented
@jcmonteiro Would you agree that I continue to work with your branch and complete with the PR? 

I'll begin with following the change requests in this PR, then create a new PR with the forked branch with my commits.

2024-03-15 08:57 UTC, jcmonteiro commented
> @jcmonteiro Would you agree that I continue to work with your branch and complete with the PR?
> 
> I'll begin with following the change requests in this PR, then create a new PR with the forked branch with my commits.

Hi @ZhenshengLee. I've been out of the loop of the robotics and ROS communities for a while now. Please feel free to take this PR in the direction that you see fit.

2024-03-15 11:10 UTC, ZhenshengLee commented
Close this and continue with #107

2024-03-15 12:23 UTC, closed without merging