Migrate to C++11 variadic templates
ros2/message_filters pull request #93
Opened 2023-04-09 19:45 UTC by cwecht

This PR mirgates message_synchronisers to variadic templates and allows for arbitrary numbers of topics.

Please note, that TimeSynchronizer had to be shruken down significantly for two reasons:

1. Implementing add0 .. add8 is now quiet hard. It has been dropped, because there is a generic alternative with add<I>
2. Variadic parameters are required to be at the end of a function signature. Therefore the queue_size parameter had to be moved to the front.

Given these changes, it might make sense to make TimeSynchronizer a template alias rather than a template class.

2024-03-22 08:48 UTC, roncapat commented
@mjcarroll any update on this?

2024-07-24 11:31 UTC, destogl approved these changes
This would be very nice to simplify and shorten the code!!

2024-07-24 11:34 UTC, ahcorde requested changes
There are many conflicts

2024-07-24 11:42 UTC, gavanderhoorn commented
> There are many conflicts

Sort-of to be expected after 1+ years in the queue, right?

2024-07-24 12:45 UTC, cwecht commented
I'm happy to update this PR. I'll have a look at it soon.

2024-07-24 20:30 UTC, ahcorde requested changes
cpplint is failing and also some tests

2024-07-26 11:30 UTC, ahcorde requested changes
`depth_image_proc` in `image_pipeline` is not compiling

```cpp
...
  image_transport::SubscriberFilter sub_depth_image_;
  message_filters::Subscriber<sensor_msgs::msg::CameraInfo> sub_info_;
  using Sync = message_filters::TimeSynchronizer<sensor_msgs::msg::Image,
      sensor_msgs::msg::CameraInfo>;
  std::shared_ptr<Sync> sync_;
...

// this line is failing
sync_ = std::make_shared<Sync>(queue_size, sub_depth_image_, sub_info_);
```

Do you mind to take a look ?

2024-07-26 15:30 UTC, ahcorde commented
I made these changes https://github.com/ros-perception/image_pipeline/pull/1015 and it's working, I would perfer not to do it, to avoid affect other users.

2024-07-27 13:27 UTC, cwecht commented
I now reintroduced the TimeSynchronizers old constructors but with a deprecation marking. That's why their are new warnings in the build.

2024-07-29 08:22 UTC, ahcorde requested changes
There are some new  warnings https://build.ros2.org/job/Rpr__message_filters__ubuntu_noble_amd64/83/clang-tidy/new/

2024-07-29 08:36 UTC, cwecht commented
> There are some new warnings https://build.ros2.org/job/Rpr__message_filters__ubuntu_noble_amd64/83/clang-tidy/new/

Yes, that's entended. The idea is to keep the old constructors in order to not break builds but mark them as "deprecated" as suggested in the [ROS 2 developer guide](https://docs.ros.org/en/rolling/The-ROS2-Project/Contributing/Developer-Guide.html#deprecation-strategy). Marking these constructors as deprecated causes the new warnings.

However, of cause we could just keep the old constructors and not mark them deprecated, but I suggest that we should remove them as they are quite redundant.

2024-07-29 08:47 UTC, ahcorde requested changes
Totally fine with the deprecation, but the warning is related with the wronly written word `deprectead` -> `deprected`.

Anyhow If there are some warnings in the tests (potencially) you should use something like:

```cpp

// suppress deprecated warnings
#if !defined(_WIN32)
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#else  // !defined(_WIN32)
# pragma warning(push)
# pragma warning(disable: 4996)
#endif

   // any calls to deprecated code

// remove warning suppression
#if !defined(_WIN32)
# pragma GCC diagnostic pop
#else  // !defined(_WIN32)
# pragma warning(pop)
#endif
```

2024-07-29 08:47 UTC, ahcorde commented on include/message_filters/time_synchronizer.hpp
> +  [[deprectead("Use variade constructor instead")]]
```suggestion
  [[deprecated("Use variade constructor instead")]]
```

2024-07-30 11:00 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21576)](http://ci.ros2.org/job/ci_linux/21576/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15865)](http://ci.ros2.org/job/ci_linux-aarch64/15865/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1074)](http://ci.ros2.org/job/ci_linux-rhel/1074/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22296)](http://ci.ros2.org/job/ci_windows/22296/)

2024-07-31 07:22 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21592)](http://ci.ros2.org/job/ci_linux/21592/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15879)](http://ci.ros2.org/job/ci_linux-aarch64/15879/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=1093)](http://ci.ros2.org/job/ci_linux-rhel/1093/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=22310)](http://ci.ros2.org/job/ci_windows/22310/)

2024-07-31 13:12 UTC, ahcorde approved these changes

2024-07-31 13:13 UTC, ahcorde commented
Thank you for the refactoring and the iterations

2024-07-31 13:13 UTC, merged